# Generated by Django 3.1.2 on 2020-10-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=200, verbose_name='Nombre del Producto')),
                ('marca', models.CharField(max_length=220, verbose_name='Marca del Producto')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('valor', models.IntegerField(verbose_name='Valor')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre_producto'],
            },
        ),
    ]
