# Generated by Django 3.1.2 on 2020-10-18 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=200, verbose_name='Rut')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del cliente')),
                ('apellido', models.CharField(max_length=220, verbose_name='Apellidos del Cliente')),
                ('correo', models.CharField(max_length=220, verbose_name='correo')),
                ('celular', models.CharField(max_length=220, verbose_name='Celular')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('fecha_creacion', models.DateField(auto_now=True, verbose_name='fecha de creacion')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre_cliente'],
            },
        ),
    ]
