# Generated by Django 3.1.2 on 2020-10-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='apellido',
            new_name='apellidos',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=100, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre_cliente',
            field=models.CharField(max_length=200, verbose_name='Nombres del cliente'),
        ),
    ]
