# Generated by Django 3.1.2 on 2020-10-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_auto_20201020_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateField(auto_now=True, verbose_name='Fecha de Registro'),
        ),
    ]
