# Generated by Django 3.1.2 on 2020-10-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_auto_20201022_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=220, verbose_name='celular'),
        ),
    ]
