# Generated by Django 3.1.2 on 2020-10-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20201023_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.IntegerField(verbose_name='celular'),
        ),
    ]
